//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_config
    {
        public string namePC { get; set; }
        public string motherboard_name { get; set; }
        public Nullable<int> motherboard_numberSlotsForRAM { get; set; }
        public Nullable<int> motherboard_numberSlotsForVideocard { get; set; }
        public Nullable<int> motherboard_numberSlotsForSATA { get; set; }
        public Nullable<int> motherboard_numberSlotsForUSB { get; set; }
        public string CPU_name { get; set; }
        public Nullable<int> CPU_numberCores { get; set; }
        public Nullable<double> CPU_frequency { get; set; }
        public string videocard_name { get; set; }
        public Nullable<int> videocard_memory { get; set; }
        public Nullable<int> videocard_frequency { get; set; }
        public Nullable<bool> videocard_additionalMeals { get; set; }
        public string SSD_name { get; set; }
        public Nullable<int> SSD_memory { get; set; }
        public Nullable<int> SSD_reading { get; set; }
        public Nullable<int> SSD_record { get; set; }
        public string HDD_name { get; set; }
        public Nullable<int> HDD_memory { get; set; }
        public Nullable<int> HDD_reading { get; set; }
        public Nullable<int> HDD_record { get; set; }
        public string fan_name { get; set; }
        public Nullable<int> fan_rotationSpeed { get; set; }
        public Nullable<int> fan_quantity { get; set; }
        public string PSU_name { get; set; }
        public Nullable<int> PSU_power { get; set; }
        public Nullable<int> PSU_numberSATAconnectors { get; set; }
        public string PC_Case_name { get; set; }
        public Nullable<int> PC_Case_length { get; set; }
        public Nullable<int> PC_Case_height { get; set; }
        public Nullable<int> PC_Case_width { get; set; }
        public Nullable<int> PC_Case_weight { get; set; }
        public string PC_Case_basicMaterial { get; set; }
        public Nullable<int> PC_Case_numberFans { get; set; }
        public Nullable<bool> PC_Case_illumination { get; set; }
    }
}
